### ISSUE TITLE
Can I fork this project?

### ISSUE THREAD

**Issue by programmablemike** [jpellerin/django-nose2#6]
Hi jpellerin,

I noticed this project hasn't been updated in quite a while and I'm looking on possibly forking it to add enhancements for newer versions of Django. However I didn't see a license in the project so I just wanted to check with you first to see if you'd be OK with that and to see if you had a software license that you prefer.

-Mike Lee

**Comment by programmablemike** [comment]
Closing the issue. I think I misunderstood what this project is doing - I was looking for a configurable Django plugin for the Nose2 test runner so I don't think there's going to be much overlap between this project and what I'm working on.

**Comment by SeanZicari** [comment]
@programmablemike What you described sounds similar. What is the package you're working on?
